-- Comptes divisionnaires à trois chiffres · rattrapage des dossiers EXISTANTS.
--
-- La Section 1 du chapitre 2 du plan SYCEBNL pose trois paliers : « les
-- comptes principaux à deux (02) chiffres ; les comptes divisionnaires à
-- trois (03) chiffres ; les comptes d'imputation de base à quatre (04)
-- chiffres ». Seul le premier palier avait été semé (migration du même jour,
-- 20260829202500) ; le palier intermédiaire, qui regroupe par exemple "401
-- Fournisseurs, dettes en compte" au-dessus de "40110000 Fournisseurs" et
-- "40130000 Sous-traitants", en était absent : la balance ne pouvait pas
-- afficher de sous-total à ce niveau.
--
-- Même règle qu'aux comptes principaux, et pour la même raison : le numéro
-- reste à TROIS chiffres, non complété à huit, pour que l'agrégation par
-- préfixe (startsWith) fonctionne. Seuls les codes à trois chiffres qui ont
-- RÉELLEMENT des comptes de détail en dessous d'eux sont repris : un code
-- sans subdivision (ex. "103 Droit d'entrée") EST le compte d'imputation
-- lui-même, déjà semé en huit chiffres.
--
-- ON CONFLICT DO NOTHING : rejouable, sans effet sur un dossier qui les a
-- déjà (créé après le changement de semis).
INSERT INTO "comptes" ("id", "tenantId", "numero", "intitule", "classe", "typeCompte", "estActif", "modeReportANouveau", "lettrable")
SELECT
  gen_random_uuid(),
  t."id",
  p."numero",
  p."intitule",
  p."classe",
  'TOTAL'::"TypeCompteDetailTotal",
  true,
  p."mode",
  false
FROM "tenants" t
CROSS JOIN (VALUES
    ('101', 'Dotation non consomptible sans droit de reprise', 'CLASSE_1'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('102', 'Dotation non consomptible avec droit de reprise', 'CLASSE_1'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('104', 'Dotation consomptible', 'CLASSE_1'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('106', 'Écarts de réévaluation', 'CLASSE_1'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('141', 'Subventions d''équipement', 'CLASSE_1'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('167', 'Fonds provenant de dons et legs d''immobilisations', 'CLASSE_1'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('185', 'Dépôts et cautionnements reçus', 'CLASSE_1'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('186', 'Intérêts courus', 'CLASSE_1'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('187', 'Dettes de location-acquisition', 'CLASSE_1'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('198', 'Autres provisions pour risques et charges', 'CLASSE_1'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('201', 'Immobilisations incorporelles', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('212', 'Brevets, licences, concessions et droits similaires', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('213', 'Logiciels et sites internet', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('218', 'Autres droits et valeurs incorporels', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('219', 'Immobilisations incorporelles en cours', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('221', 'Terrains agricoles et forestiers', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('222', 'Terrains nus', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('223', 'Terrains bâtis', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('224', 'Travaux de mise en valeur des terrains', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('226', 'Terrains aménagés', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('228', 'Autres terrains', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('229', 'Aménagements de terrains en cours', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('231', 'Bâtiments industriels, agricoles, administratifs, commerciaux, religieux et autres sur sol propre', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('232', 'Bâtiments industriels, agricoles, administratifs, commerciaux, religieux et autres sur sol d''autrui', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('233', 'Ouvrages d''infrastructure', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('234', 'Aménagements, agencements et installations techniques', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('235', 'Aménagements de bureaux et assimilés', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('238', 'Autres installations et agencements', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('239', 'Bâtiments, aménagements, agencements et installations en cours', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('241', 'Matériel et outillage industriel et commercial', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('242', 'Matériel et outillage agricole', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('244', 'Matériel et mobilier', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('245', 'Matériel de transport', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('246', 'Actifs biologiques', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('247', 'Agencements, aménagements du matériel et des actifs biologiques', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('248', 'Autres matériels et mobiliers', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('249', 'Matériels et actifs biologiques en cours', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('271', 'Prêts et créances', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('272', 'Prêts au personnel', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('273', 'Créances sur l''Etat', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('274', 'Titres immobilisés', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('275', 'Dépôts et cautionnements versés', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('276', 'Intérêts courus', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('278', 'Immobilisations financières diverses', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('281', 'Amortissements des immobilisations incorporelles', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('282', 'Amortissements des terrains', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('283', 'Amortissements des bâtiments, installations techniques et agencements', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('284', 'Amortissements du matériel', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('290', 'Dépréciations des immobilisations destinées à la vente provenant de dons et legs non encore reçus et d''usufruit temporaire', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('291', 'Dépréciations des immobilisations incorporelles', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('292', 'Dépréciations des terrains', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('293', 'Dépréciations des bâtiments, installations techniques et agencements', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('294', 'Dépréciations du matériel, du mobilier et de l''actif biologique', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('295', 'Dépréciations des avances et acomptes versés sur immobilisations', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('296', 'Dépréciations des titres de participation', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('297', 'Dépréciations des autres immobilisations financières', 'CLASSE_2'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('335', 'Emballages', 'CLASSE_3'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('363', 'Actifs biologiques', 'CLASSE_3'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('377', 'Stocks en consignation ou en dépôt', 'CLASSE_3'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('401', 'Fournisseurs, dettes en compte', 'CLASSE_4'::"ClasseCompte", 'DETAIL'::"ModeReportANouveau"),
    ('402', 'Fournisseurs, effets à payer', 'CLASSE_4'::"ClasseCompte", 'DETAIL'::"ModeReportANouveau"),
    ('408', 'Fournisseurs, factures non parvenues', 'CLASSE_4'::"ClasseCompte", 'DETAIL'::"ModeReportANouveau"),
    ('409', 'Fournisseurs débiteurs', 'CLASSE_4'::"ClasseCompte", 'DETAIL'::"ModeReportANouveau"),
    ('413', 'Adhérents, Clients-usagers, chèques, effets et autres valeurs impayés', 'CLASSE_4'::"ClasseCompte", 'DETAIL'::"ModeReportANouveau"),
    ('416', 'Créances, adhérents, clients-usagers litigieuses ou douteuses', 'CLASSE_4'::"ClasseCompte", 'DETAIL'::"ModeReportANouveau"),
    ('418', 'Adhérents, clients-usagers produits à recevoir', 'CLASSE_4'::"ClasseCompte", 'DETAIL'::"ModeReportANouveau"),
    ('419', 'Adhérents, Clients-usagers créditeurs', 'CLASSE_4'::"ClasseCompte", 'DETAIL'::"ModeReportANouveau"),
    ('421', 'Avances et acomptes', 'CLASSE_4'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('423', 'Oppositions, saisies arrêts', 'CLASSE_4'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('424', 'Œuvres sociales internes', 'CLASSE_4'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('425', 'Représentants du personnel', 'CLASSE_4'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('428', 'Personnel, charges à payer et produits à recevoir', 'CLASSE_4'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('431', 'Sécurité sociale', 'CLASSE_4'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('432', 'Caisses de retraite', 'CLASSE_4'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('433', 'Autres organismes sociaux', 'CLASSE_4'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('438', 'Organismes sociaux, charges à payer et produits à recevoir', 'CLASSE_4'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('442', 'Etat, autres impôts et taxes', 'CLASSE_4'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('443', 'Etat, T.V.A. Facturée', 'CLASSE_4'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('444', 'T.V.A. due ou crédit de T.V.A.', 'CLASSE_4'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('445', 'T.V.A. Récupérable', 'CLASSE_4'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('447', 'Etat, impôts retenus à la source', 'CLASSE_4'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('448', 'État, charges à payer et produits à recevoir', 'CLASSE_4'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('449', 'Etat, créances et dettes diverses', 'CLASSE_4'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('451', 'Associations et assimilées', 'CLASSE_4'::"ClasseCompte", 'DETAIL'::"ModeReportANouveau"),
    ('452', 'Fondations et assimilées', 'CLASSE_4'::"ClasseCompte", 'DETAIL'::"ModeReportANouveau"),
    ('453', 'Ordres professionnels', 'CLASSE_4'::"ClasseCompte", 'DETAIL'::"ModeReportANouveau"),
    ('454', 'Organisations politiques', 'CLASSE_4'::"ClasseCompte", 'DETAIL'::"ModeReportANouveau"),
    ('455', 'Organisations syndicales', 'CLASSE_4'::"ClasseCompte", 'DETAIL'::"ModeReportANouveau"),
    ('456', 'Organisations religieuses, apporteurs', 'CLASSE_4'::"ClasseCompte", 'DETAIL'::"ModeReportANouveau"),
    ('457', 'Mécènes, bénévoles et assimilés', 'CLASSE_4'::"ClasseCompte", 'DETAIL'::"ModeReportANouveau"),
    ('469', 'Fonds d''administration à recevoir', 'CLASSE_4'::"ClasseCompte", 'DETAIL'::"ModeReportANouveau"),
    ('471', 'Débiteurs et créditeurs divers', 'CLASSE_4'::"ClasseCompte", 'DETAIL'::"ModeReportANouveau"),
    ('472', 'Créances et dettes sur titres de placement', 'CLASSE_4'::"ClasseCompte", 'DETAIL'::"ModeReportANouveau"),
    ('473', 'Organismes nationaux et internationaux – subventions à recevoir', 'CLASSE_4'::"ClasseCompte", 'DETAIL'::"ModeReportANouveau"),
    ('474', 'Compte de répartition périodique des charges et des produits', 'CLASSE_4'::"ClasseCompte", 'DETAIL'::"ModeReportANouveau"),
    ('478', 'Écarts de conversion - actif', 'CLASSE_4'::"ClasseCompte", 'DETAIL'::"ModeReportANouveau"),
    ('481', 'Fournisseurs d''investissements', 'CLASSE_4'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('485', 'Créances sur cessions d''immobilisations', 'CLASSE_4'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('486', 'Dettes et créances des legs et dons d''immobilisations', 'CLASSE_4'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('488', 'Autres créances hors activités ordinaires', 'CLASSE_4'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('491', 'Adhérents et clients-usagers, dépréciations', 'CLASSE_4'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('498', 'Créances H.A.O.', 'CLASSE_4'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('499', 'Provisions pour risques et charges à court terme', 'CLASSE_4'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('502', 'Actions', 'CLASSE_5'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('503', 'Obligations', 'CLASSE_5'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('504', 'Bons de souscription', 'CLASSE_5'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('518', 'Valeurs à encaisser, autres', 'CLASSE_5'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('521', 'Banques locales', 'CLASSE_5'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('526', 'Banques, intérêts courus', 'CLASSE_5'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('536', 'Établissements financiers, intérêts courus', 'CLASSE_5'::"ClasseCompte", 'SOLDE'::"ModeReportANouveau"),
    ('603', 'Variations des stocks de biens achetés et reçus en dons en nature à distribuer', 'CLASSE_6'::"ClasseCompte", 'AUCUN'::"ModeReportANouveau"),
    ('606', 'Achats autres activités', 'CLASSE_6'::"ClasseCompte", 'AUCUN'::"ModeReportANouveau"),
    ('681', 'Dotations aux amortissements d''exploitation', 'CLASSE_6'::"ClasseCompte", 'AUCUN'::"ModeReportANouveau"),
    ('704', 'Revenus liés à la générosité', 'CLASSE_7'::"ClasseCompte", 'AUCUN'::"ModeReportANouveau"),
    ('705', 'Ventes de marchandises, de services et de produits finis', 'CLASSE_7'::"ClasseCompte", 'AUCUN'::"ModeReportANouveau"),
    ('708', 'Autres revenus', 'CLASSE_7'::"ClasseCompte", 'AUCUN'::"ModeReportANouveau"),
    ('754', 'Dons en nature courants', 'CLASSE_7'::"ClasseCompte", 'AUCUN'::"ModeReportANouveau"),
    ('758', 'Produits divers', 'CLASSE_7'::"ClasseCompte", 'AUCUN'::"ModeReportANouveau")
) AS p("numero", "intitule", "classe", "mode")
ON CONFLICT ("tenantId", "numero") DO NOTHING;
